const state={files:[],processing:false,preset:"web"};
const $=id=>document.getElementById(id);
const els={dropZone:$("dropZone"),chooseBtn:$("chooseBtn"),fileInput:$("fileInput"),fileList:$("fileList"),emptyState:$("emptyState"),fileCount:$("fileCount"),totalOriginal:$("totalOriginal"),totalOutput:$("totalOutput"),totalSaved:$("totalSaved"),maxPx:$("maxPx"),maxMb:$("maxMb"),convertPng:$("convertPng"),processBtn:$("processBtn"),downloadAllBtn:$("downloadAllBtn"),resetBtn:$("resetBtn"),statusText:$("statusText"),progressText:$("progressText"),progressBar:$("progressBar")};
const SUPPORTED_TYPES=new Set(["image/jpeg","image/png","image/webp"]);
function formatBytes(bytes){if(!Number.isFinite(bytes)||bytes<=0)return"0 B";const units=["B","KB","MB","GB"];let v=bytes,i=0;while(v>=1024&&i<units.length-1){v/=1024;i++}const d=i===0?0:v>=100?0:v>=10?1:2;return`${v.toFixed(d)} ${units[i]}`}
function getMode(){return document.querySelector('input[name="resizeMode"]:checked').value}
function setMode(mode){const r=document.querySelector(`input[name="resizeMode"][value="${mode}"]`);if(r)r.checked=true;updateSettingState()}
function updateSettingState(){const m=getMode();els.maxPx.disabled=m==="size";els.maxMb.disabled=m==="pixels";els.maxPx.closest(".input-unit").classList.toggle("disabled",els.maxPx.disabled);els.maxMb.closest(".input-unit").classList.toggle("disabled",els.maxMb.disabled)}
function applyPreset(name){state.preset=name;document.querySelectorAll(".preset").forEach(b=>b.classList.toggle("active",b.dataset.preset===name));if(name==="web"){els.maxPx.value=1920;els.maxMb.value=2;setMode("both")}else if(name==="email"){els.maxPx.value=1600;els.maxMb.value=1;setMode("both")}}
function markCustom(){state.preset="custom";document.querySelectorAll(".preset").forEach(b=>b.classList.toggle("active",b.dataset.preset==="custom"))}
function addFiles(list){if(state.processing)return;for(const file of [...list].filter(f=>SUPPORTED_TYPES.has(f.type))){if(state.files.some(x=>x.file.name===file.name&&x.file.size===file.size&&x.file.lastModified===file.lastModified))continue;state.files.push({id:(crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`),file,originalUrl:URL.createObjectURL(file),outputBlob:null,outputName:null,outputUrl:null,error:null,status:"ready"})}renderList();updateSummary()}
function removeFile(id){const i=state.files.findIndex(x=>x.id===id);if(i<0||state.processing)return;const item=state.files[i];URL.revokeObjectURL(item.originalUrl);if(item.outputUrl)URL.revokeObjectURL(item.outputUrl);state.files.splice(i,1);renderList();updateSummary()}
function resetAll(){if(state.processing)return;for(const item of state.files){URL.revokeObjectURL(item.originalUrl);if(item.outputUrl)URL.revokeObjectURL(item.outputUrl)}state.files=[];els.fileInput.value="";applyPreset("web");els.convertPng.checked=true;setProgress(0,"準備就緒");renderList();updateSummary()}
function renderList(){els.fileCount.textContent=`${state.files.length} 張`;els.emptyState.hidden=state.files.length>0;els.fileList.hidden=state.files.length===0;els.fileList.innerHTML="";state.files.forEach(item=>{const row=document.createElement("div");row.className="file-item";const thumb=document.createElement("img");thumb.className="thumb";thumb.src=item.originalUrl;thumb.alt="";const meta=document.createElement("div");meta.className="file-meta";const name=document.createElement("div");name.className="file-name";name.textContent=item.file.name;const sub=document.createElement("div");sub.className="file-sub";sub.textContent=item.outputBlob?`${formatBytes(item.file.size)} → ${formatBytes(item.outputBlob.size)}`:formatBytes(item.file.size);meta.append(name,sub);const status=document.createElement("div");status.className="file-status";if(item.status==="done"){status.textContent="完成";status.classList.add("done")}else if(item.status==="error"){status.textContent="失敗";status.classList.add("error");status.title=item.error||""}else if(item.status==="processing")status.textContent="處理中";else status.textContent="等待";let action;if(item.outputBlob){action=document.createElement("button");action.className="download-btn";action.type="button";action.textContent="下載";action.onclick=()=>downloadBlob(item.outputBlob,item.outputName)}else{action=document.createElement("button");action.className="icon-btn";action.type="button";action.textContent="×";action.title="移除";action.disabled=state.processing;action.onclick=()=>removeFile(item.id)}row.append(thumb,meta,status,action);els.fileList.append(row)});els.processBtn.disabled=state.files.length===0||state.processing;els.downloadAllBtn.disabled=!state.files.some(x=>x.outputBlob)||state.processing}
function updateSummary(){const original=state.files.reduce((s,x)=>s+x.file.size,0),outs=state.files.filter(x=>x.outputBlob),output=outs.reduce((s,x)=>s+x.outputBlob.size,0);els.totalOriginal.textContent=formatBytes(original);els.totalOutput.textContent=outs.length?formatBytes(output):"0 MB";if(outs.length&&original>0){const co=outs.reduce((s,x)=>s+x.file.size,0),saved=Math.max(0,co-output),pct=co?saved/co*100:0;els.totalSaved.textContent=`${pct.toFixed(1)}%`}else els.totalSaved.textContent="0%"}
function setProgress(percent,text){const p=Math.max(0,Math.min(100,percent));els.progressBar.style.width=`${p}%`;els.progressText.textContent=`${Math.round(p)}%`;els.statusText.textContent=text}
async function fileToBitmap(file){if("createImageBitmap" in window){try{return await createImageBitmap(file,{imageOrientation:"from-image"})}catch(_){return await createImageBitmap(file)}}return await new Promise((res,rej)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);res(img)};img.onerror=()=>{URL.revokeObjectURL(url);rej(new Error("無法讀取圖片"))};img.src=url})}
function canvasForBitmap(bitmap,maxPx,limit){const sw=bitmap.width,sh=bitmap.height;let w=sw,h=sh;if(limit&&maxPx>0&&Math.max(sw,sh)>maxPx){const r=maxPx/Math.max(sw,sh);w=Math.max(1,Math.round(sw*r));h=Math.max(1,Math.round(sh*r))}const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d",{alpha:true});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.drawImage(bitmap,0,0,w,h);return c}
function canvasToBlob(canvas,type,quality){return new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error("瀏覽器無法產生輸出圖片")),type,quality))}
function hasTransparency(canvas){const ctx=canvas.getContext("2d",{willReadFrequently:true}),w=canvas.width,h=canvas.height,total=w*h,step=Math.max(1,Math.floor(Math.sqrt(total/40000)));for(let y=0;y<h;y+=step){const row=ctx.getImageData(0,y,w,1).data;for(let x=0;x<w;x+=step)if(row[x*4+3]<255)return true}return false}
async function binarySearchQuality(canvas,type,maxBytes){let low=.35,high=.95,best=null;for(let i=0;i<8;i++){const q=(low+high)/2,blob=await canvasToBlob(canvas,type,q);if(blob.size<=maxBytes){best=blob;low=q}else high=q}if(!best)best=await canvasToBlob(canvas,type,.35);return best}
function resizedCanvas(src,scale){const c=document.createElement("canvas");c.width=Math.max(1,Math.round(src.width*scale));c.height=Math.max(1,Math.round(src.height*scale));const ctx=c.getContext("2d");ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.drawImage(src,0,0,c.width,c.height);return c}
async function shrinkUntilTarget(canvas,type,target){let working=canvas,blob=null;for(let i=0;i<12;i++){blob=type==="image/png"?await canvasToBlob(working,type):await binarySearchQuality(working,type,target);if(blob.size<=target)return blob;if(Math.max(working.width,working.height)<=320)break;working=resizedCanvas(working,.9)}return blob}
function makeOutputName(name,type){const dot=name.lastIndexOf("."),base=dot>=0?name.slice(0,dot):name,ext=type==="image/jpeg"?".jpg":type==="image/webp"?".webp":".png";return base+ext}
async function processImage(item,s){const bitmap=await fileToBitmap(item.file);try{const limit=s.mode==="pixels"||s.mode==="both";let canvas=canvasForBitmap(bitmap,s.maxPx,limit),type=item.file.type;if(s.mode==="pixels"){const blob=type==="image/png"?await canvasToBlob(canvas,type):await canvasToBlob(canvas,type,.9);return{blob,name:makeOutputName(item.file.name,type)}}const target=Math.max(1,Math.floor(s.maxMb*1024*1024));if(type==="image/jpeg"||type==="image/webp"){const blob=await shrinkUntilTarget(canvas,type,target);return{blob,name:makeOutputName(item.file.name,type)}}if(type==="image/png"){const png=await canvasToBlob(canvas,"image/png");if(png.size<=target)return{blob:png,name:makeOutputName(item.file.name,"image/png")};if(!hasTransparency(canvas)&&s.convertPng){const blob=await shrinkUntilTarget(canvas,"image/jpeg",target);return{blob,name:makeOutputName(item.file.name,"image/jpeg")}}const blob=await shrinkUntilTarget(canvas,"image/png",target);return{blob,name:makeOutputName(item.file.name,"image/png")}}throw new Error("不支援的圖片格式")}finally{if(bitmap&&typeof bitmap.close==="function")bitmap.close()}}
function getSettings(){const mode=getMode(),maxPx=Number(els.maxPx.value),maxMb=Number(els.maxMb.value);if((mode==="pixels"||mode==="both")&&(!Number.isFinite(maxPx)||maxPx<100))throw new Error("最大長邊請輸入至少 100 px。");if((mode==="size"||mode==="both")&&(!Number.isFinite(maxMb)||maxMb<=0))throw new Error("最大檔案大小請輸入大於 0 的 MB 數值。");return{mode,maxPx,maxMb,convertPng:els.convertPng.checked}}
async function processAll(){if(!state.files.length||state.processing)return;let settings;try{settings=getSettings()}catch(e){alert(e.message);return}state.processing=true;renderList();let done=0;for(const item of state.files){if(item.outputUrl){URL.revokeObjectURL(item.outputUrl);item.outputUrl=null}item.outputBlob=null;item.outputName=null;item.error=null;item.status="processing";renderList();setProgress(done/state.files.length*100,`正在處理：${item.file.name}`);try{const r=await processImage(item,settings);item.outputBlob=r.blob;item.outputName=r.name;item.outputUrl=URL.createObjectURL(r.blob);item.status="done"}catch(e){item.error=e instanceof Error?e.message:String(e);item.status="error"}done++;updateSummary();renderList();setProgress(done/state.files.length*100,`已完成 ${done} / ${state.files.length}`);await new Promise(r=>setTimeout(r,0))}state.processing=false;renderList();updateSummary();const ok=state.files.filter(x=>x.outputBlob).length,fail=state.files.filter(x=>x.status==="error").length;setProgress(100,fail?`完成：成功 ${ok} 張，失敗 ${fail} 張`:`完成：${ok} 張圖片`)}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name||"image";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function downloadAllZip(){const outs=state.files.filter(x=>x.outputBlob);if(!outs.length)return;if(typeof JSZip==="undefined"){alert("ZIP 模組載入失敗");return}els.downloadAllBtn.disabled=true;els.statusText.textContent="正在建立 ZIP...";try{const zip=new JSZip(),used=new Set();for(const item of outs){let name=item.outputName;if(used.has(name)){const dot=name.lastIndexOf("."),base=dot>=0?name.slice(0,dot):name,ext=dot>=0?name.slice(dot):"";let i=2;while(used.has(`${base}_${i}${ext}`))i++;name=`${base}_${i}${ext}`}used.add(name);zip.file(name,item.outputBlob)}const blob=await zip.generateAsync({type:"blob"},m=>els.statusText.textContent=`正在建立 ZIP：${m.percent.toFixed(0)}%`);downloadBlob(blob,"resized_images.zip");els.statusText.textContent="ZIP 已建立"}finally{els.downloadAllBtn.disabled=false}}
els.chooseBtn.addEventListener("click",e=>{e.stopPropagation();els.fileInput.click()});els.dropZone.addEventListener("click",e=>{if(e.target!==els.chooseBtn)els.fileInput.click()});els.dropZone.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();els.fileInput.click()}});els.fileInput.addEventListener("change",()=>addFiles(els.fileInput.files));["dragenter","dragover"].forEach(t=>els.dropZone.addEventListener(t,e=>{e.preventDefault();els.dropZone.classList.add("dragover")}));["dragleave","drop"].forEach(t=>els.dropZone.addEventListener(t,e=>{e.preventDefault();els.dropZone.classList.remove("dragover")}));els.dropZone.addEventListener("drop",e=>addFiles(e.dataTransfer.files));document.querySelectorAll(".preset").forEach(b=>b.addEventListener("click",()=>applyPreset(b.dataset.preset)));document.querySelectorAll('input[name="resizeMode"]').forEach(r=>r.addEventListener("change",()=>{markCustom();updateSettingState()}));[els.maxPx,els.maxMb].forEach(i=>i.addEventListener("input",markCustom));els.convertPng.addEventListener("change",markCustom);els.processBtn.addEventListener("click",processAll);els.downloadAllBtn.addEventListener("click",downloadAllZip);els.resetBtn.addEventListener("click",resetAll);window.addEventListener("beforeunload",()=>{for(const i of state.files){URL.revokeObjectURL(i.originalUrl);if(i.outputUrl)URL.revokeObjectURL(i.outputUrl)}});applyPreset("web");renderList();updateSummary();
