const S={files:[],processing:false,editorIndex:-1,editorBitmap:null,editorRatio:null,editorCrop:"original",editorW:0,editorH:0,dragging:false};
const $=id=>document.getElementById(id);
const E={drop:$("dropZone"),empty:$("emptyDrop"),selected:$("selectedArea"),count:$("selectedCount"),grid:$("thumbGrid"),file:$("fileInput"),choose:$("chooseBtn"),add:$("addMoreBtn"),maxPx:$("maxPx"),maxMb:$("maxMb"),convert:$("convertPng"),process:$("processBtn"),download:$("downloadBtn"),reset:$("resetBtn"),orig:$("totalOriginal"),out:$("totalOutput"),saved:$("totalSaved"),bar:$("progressBar"),status:$("statusText"),pct:$("progressText"),modal:$("editorModal"),ename:$("editorName"),canvas:$("previewCanvas"),stage:$("previewStage"),handle:$("resizeHandle"),odim:$("originalDim"),cdim:$("currentDim"),ew:$("editWidth"),eh:$("editHeight"),lock:$("lockRatio"),slider:$("scaleSlider"),scaleVal:$("scaleValue"),apply:$("applyEditBtn"),downloadEdit:$("downloadEditBtn"),fit1920:$("fit1920")};
const TYPES=new Set(["image/jpeg","image/png","image/webp"]);
const fmt=b=>{if(!b)return"0 B";let v=b,u=["B","KB","MB","GB"],i=0;while(v>=1024&&i<u.length-1){v/=1024;i++}return`${v.toFixed(i?1:0)} ${u[i]}`};
function mode(){return document.querySelector('input[name="mode"]:checked').value}
function setProgress(p,t){E.bar.style.width=p+"%";E.pct.textContent=Math.round(p)+"%";E.status.textContent=t}
function applyPreset(n){document.querySelectorAll(".preset").forEach(x=>x.classList.toggle("active",x.dataset.preset===n));if(n==="web"){E.maxPx.value=1920;E.maxMb.value=2;document.querySelector('[value="both"]').checked=true}if(n==="email"){E.maxPx.value=1600;E.maxMb.value=1;document.querySelector('[value="both"]').checked=true}}
function addFiles(list){for(const f of [...list]){if(!TYPES.has(f.type))continue;if(S.files.some(x=>x.file.name===f.name&&x.file.size===f.size&&x.file.lastModified===f.lastModified))continue;S.files.push({file:f,url:URL.createObjectURL(f),blob:null,name:null,error:null,custom:null})}render()}
function removeAt(i){const x=S.files[i];URL.revokeObjectURL(x.url);if(x.outUrl)URL.revokeObjectURL(x.outUrl);S.files.splice(i,1);render()}
function render(){E.empty.hidden=S.files.length>0;E.selected.hidden=!S.files.length;E.count.textContent=S.files.length;E.grid.innerHTML="";S.files.forEach((x,i)=>{const c=document.createElement("div");c.className="thumb-card";c.innerHTML=`<img src="${x.url}" alt=""><div class="thumb-name"></div><div class="thumb-size">${fmt(x.file.size)}${x.blob?` → ${fmt(x.blob.size)}`:""}</div><div class="thumb-actions"><button class="edit-btn">調整</button><button class="remove-btn">移除</button></div>`;c.querySelector(".thumb-name").textContent=x.file.name;c.querySelector(".edit-btn").onclick=()=>openEditor(i);c.querySelector(".remove-btn").onclick=()=>removeAt(i);E.grid.appendChild(c)});E.process.disabled=!S.files.length||S.processing;updateSummary();updateDownload()}
function updateSummary(){const a=S.files.reduce((s,x)=>s+x.file.size,0),done=S.files.filter(x=>x.blob),b=done.reduce((s,x)=>s+x.blob.size,0),oa=done.reduce((s,x)=>s+x.file.size,0);E.orig.textContent=fmt(a);E.out.textContent=done.length?fmt(b):"0 MB";E.saved.textContent=oa?Math.max(0,(oa-b)/oa*100).toFixed(1)+"%":"0%"}
function updateDownload(){const d=S.files.filter(x=>x.blob);E.download.disabled=!d.length||S.processing;E.download.textContent=d.length===1?"下載圖片":d.length>1?`全部下載 ZIP（${d.length} 張）`:"下載處理結果"}
async function bitmap(file){try{return await createImageBitmap(file,{imageOrientation:"from-image"})}catch{return await createImageBitmap(file)}}
function newCanvas(w,h){const c=document.createElement("canvas");c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c}
function drawContain(src,w,h){const c=newCanvas(w,h),ctx=c.getContext("2d");ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.drawImage(src,0,0,w,h);return c}
function cropCanvas(src,ratio){if(!ratio)return drawContain(src,src.width,src.height);const sw=src.width,sh=src.height,sr=sw/sh;let sx=0,sy=0,cw=sw,ch=sh;if(sr>ratio){cw=sh*ratio;sx=(sw-cw)/2}else{ch=sw/ratio;sy=(sh-ch)/2}const c=newCanvas(cw,ch);c.getContext("2d").drawImage(src,sx,sy,cw,ch,0,0,c.width,c.height);return c}
function toBlob(c,type,q){return new Promise((r,j)=>c.toBlob(b=>b?r(b):j(new Error("無法產生圖片")),type,q))}
async function searchQ(c,type,max){let lo=.35,hi=.95,best=null;for(let i=0;i<8;i++){let q=(lo+hi)/2,b=await toBlob(c,type,q);if(b.size<=max){best=b;lo=q}else hi=q}return best||await toBlob(c,type,.35)}
async function shrink(c,type,target){let cur=c,b=null;for(let i=0;i<12;i++){b=type==="image/png"?await toBlob(cur,type):await searchQ(cur,type,target);if(b.size<=target)return b;if(Math.max(cur.width,cur.height)<=320)break;cur=drawContain(cur,cur.width*.9,cur.height*.9)}return b}
function outName(name,type){const p=name.lastIndexOf("."),base=p>=0?name.slice(0,p):name,ext=type==="image/jpeg"?".jpg":type==="image/webp"?".webp":".png";return base+ext}
function alpha(c){const ctx=c.getContext("2d",{willReadFrequently:true}),w=c.width,h=c.height,step=Math.max(1,Math.floor(Math.sqrt(w*h/30000)));for(let y=0;y<h;y+=step){let d=ctx.getImageData(0,y,w,1).data;for(let x=0;x<w;x+=step)if(d[x*4+3]<255)return true}return false}
async function processOne(x){const b=await bitmap(x.file);try{let c;if(x.custom){c=cropCanvas(b,x.custom.ratio);c=drawContain(c,x.custom.width,x.custom.height)}else{const m=mode(),max=Number(E.maxPx.value),long=Math.max(b.width,b.height);if((m==="pixels"||m==="both")&&long>max){const r=max/long;c=drawContain(b,b.width*r,b.height*r)}else c=drawContain(b,b.width,b.height)}const m=mode(),target=Number(E.maxMb.value)*1024*1024,t=x.file.type;if(m==="pixels"){const blob=await toBlob(c,t,t==="image/png"?undefined:.9);return{blob,name:outName(x.file.name,t)}}if(t==="image/png"){let p=await toBlob(c,"image/png");if(p.size<=target)return{blob:p,name:outName(x.file.name,"image/png")};if(!alpha(c)&&E.convert.checked){const blob=await shrink(c,"image/jpeg",target);return{blob,name:outName(x.file.name,"image/jpeg")}}return{blob:await shrink(c,"image/png",target),name:outName(x.file.name,"image/png")}}return{blob:await shrink(c,t,target),name:outName(x.file.name,t)}}finally{b.close&&b.close()}}
async function processAll(){if(!S.files.length)return;S.processing=true;render();for(let i=0;i<S.files.length;i++){const x=S.files[i];setProgress(i/S.files.length*100,`正在處理：${x.file.name}`);try{const r=await processOne(x);x.blob=r.blob;x.name=r.name;x.error=null}catch(e){x.error=e.message}render();await new Promise(r=>setTimeout(r,0))}S.processing=false;setProgress(100,"處理完成");render()}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1200)}
async function downloadResults(){const d=S.files.filter(x=>x.blob);if(d.length===1)return downloadBlob(d[0].blob,d[0].name);const z=new JSZip(),used=new Set();for(const x of d){let n=x.name,k=2,p=n.lastIndexOf("."),base=p>=0?n.slice(0,p):n,ext=p>=0?n.slice(p):"";while(used.has(n))n=`${base}_${k++}${ext}`;used.add(n);z.file(n,x.blob)}downloadBlob(await z.generateAsync({type:"blob"}),"resized_images.zip")}
function reset(){S.files.forEach(x=>{URL.revokeObjectURL(x.url);if(x.outUrl)URL.revokeObjectURL(x.outUrl)});S.files=[];setProgress(0,"準備就緒");render()}
async function openEditor(i){S.editorIndex=i;const x=S.files[i];if(S.editorBitmap&&S.editorBitmap.close)S.editorBitmap.close();S.editorBitmap=await bitmap(x.file);S.editorRatio=S.editorBitmap.width/S.editorBitmap.height;S.editorCrop=x.custom?.ratio||null;S.editorW=x.custom?.width||S.editorBitmap.width;S.editorH=x.custom?.height||S.editorBitmap.height;E.ename.textContent=x.file.name;E.odim.textContent=`${S.editorBitmap.width} × ${S.editorBitmap.height}`;E.modal.hidden=false;document.body.style.overflow="hidden";syncEditor()}
function closeEditor(){E.modal.hidden=true;document.body.style.overflow="";if(S.editorBitmap&&S.editorBitmap.close)S.editorBitmap.close();S.editorBitmap=null}
function cropRatio(){return S.editorCrop}
function syncEditor(){if(!S.editorBitmap)return;E.ew.value=Math.round(S.editorW);E.eh.value=Math.round(S.editorH);E.cdim.textContent=`${Math.round(S.editorW)} × ${Math.round(S.editorH)}`;let pct=Math.round(S.editorW/S.editorBitmap.width*100);E.slider.value=Math.max(10,Math.min(100,pct));E.scaleVal.textContent=pct+"%";const src=cropCanvas(S.editorBitmap,cropRatio());const c=E.canvas;c.width=Math.round(S.editorW);c.height=Math.round(S.editorH);c.getContext("2d").drawImage(src,0,0,c.width,c.height);document.querySelectorAll(".ratio").forEach(b=>b.classList.toggle("active",(b.dataset.ratio==="original"&&!S.editorCrop)||Number(b.dataset.ratio)===S.editorCrop))}
function setWidth(w){S.editorW=Math.max(1,Math.round(w));if(E.lock.checked){const r=S.editorCrop||S.editorRatio;S.editorH=Math.round(S.editorW/r)}syncEditor()}
function setHeight(h){S.editorH=Math.max(1,Math.round(h));if(E.lock.checked){const r=S.editorCrop||S.editorRatio;S.editorW=Math.round(S.editorH*r)}syncEditor()}
function setScale(p){S.editorW=Math.round(S.editorBitmap.width*p/100);const r=S.editorCrop||S.editorRatio;S.editorH=Math.round(S.editorW/r);syncEditor()}
async function applyEdit(download=false){const i=S.editorIndex,x=S.files[i];x.custom={width:Math.round(S.editorW),height:Math.round(S.editorH),ratio:S.editorCrop};const r=await processOne(x);x.blob=r.blob;x.name=r.name;render();if(download)downloadBlob(x.blob,x.name);else closeEditor()}
E.choose.onclick=()=>E.file.click();E.add.onclick=()=>E.file.click();E.file.onchange=()=>addFiles(E.file.files);
["dragenter","dragover"].forEach(t=>E.drop.addEventListener(t,e=>{e.preventDefault();E.drop.classList.add("dragover")}));["dragleave","drop"].forEach(t=>E.drop.addEventListener(t,e=>{e.preventDefault();E.drop.classList.remove("dragover")}));E.drop.addEventListener("drop",e=>addFiles(e.dataTransfer.files));
document.querySelectorAll(".preset").forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));E.process.onclick=processAll;E.download.onclick=downloadResults;E.reset.onclick=reset;
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=closeEditor);E.ew.onchange=()=>setWidth(Number(E.ew.value));E.eh.onchange=()=>setHeight(Number(E.eh.value));E.slider.oninput=()=>setScale(Number(E.slider.value));
document.querySelectorAll("[data-scale]").forEach(b=>b.onclick=()=>setScale(Number(b.dataset.scale)));E.fit1920.onclick=()=>setWidth(Math.min(1920,S.editorBitmap.width));
document.querySelectorAll(".ratio").forEach(b=>b.onclick=()=>{S.editorCrop=b.dataset.ratio==="original"?null:Number(b.dataset.ratio);const r=S.editorCrop||S.editorRatio;S.editorH=Math.round(S.editorW/r);syncEditor()});
E.apply.onclick=()=>applyEdit(false);E.downloadEdit.onclick=()=>applyEdit(true);
E.handle.addEventListener("pointerdown",e=>{S.dragging=true;E.handle.setPointerCapture(e.pointerId);e.preventDefault()});
E.handle.addEventListener("pointermove",e=>{if(!S.dragging)return;const rect=E.canvas.getBoundingClientRect(),scaleX=S.editorW/rect.width,newDisplayW=Math.max(80,e.clientX-rect.left);setWidth(newDisplayW*scaleX)});
E.handle.addEventListener("pointerup",()=>S.dragging=false);
render();applyPreset("web");