const S={files:[],processing:false,editorIndex:-1,editorBitmap:null,editorRatio:null,editorCrop:null,editorW:0,editorH:0,freeCrop:false,cropRect:null,previewScale:1,pointerMode:null,startPoint:null,startCropRect:null,drawingNewCrop:false,rotation:0};
const $=id=>document.getElementById(id);
const E={drop:$("dropZone"),empty:$("emptyDrop"),selected:$("selectedArea"),count:$("selectedCount"),grid:$("thumbGrid"),file:$("fileInput"),choose:$("chooseBtn"),add:$("addMoreBtn"),maxPx:$("maxPx"),maxMb:$("maxMb"),convert:$("convertPng"),process:$("processBtn"),download:$("downloadBtn"),reset:$("resetBtn"),orig:$("totalOriginal"),out:$("totalOutput"),saved:$("totalSaved"),bar:$("progressBar"),status:$("statusText"),pct:$("progressText"),modal:$("editorModal"),ename:$("editorName"),canvas:$("previewCanvas"),stage:$("previewStage"),resizeHandle:$("resizeHandle"),cropBox:$("cropBox"),cropBoxSize:$("cropBoxSize"),odim:$("originalDim"),cdim:$("currentDim"),cropInfoRow:$("cropInfoRow"),cropDim:$("cropDim"),ew:$("editWidth"),eh:$("editHeight"),lock:$("lockRatio"),slider:$("scaleSlider"),scaleVal:$("scaleValue"),apply:$("applyEditBtn"),downloadEdit:$("downloadEditBtn"),fit1920:$("fit1920"),freeCropBtn:$("freeCropBtn"),newCropBtn:$("newCropBtn"),resetCropBtn:$("resetCropBtn"),rotateLeftBtn:$("rotateLeftBtn"),rotateRightBtn:$("rotateRightBtn"),finalPreviewCanvas:$("finalPreviewCanvas"),finalPreviewDim:$("finalPreviewDim")};
const TYPES=new Set(["image/jpeg","image/png","image/webp"]);
function fmt(bytes){if(!bytes)return"0 B";let v=bytes,i=0;const u=["B","KB","MB","GB"];while(v>=1024&&i<u.length-1){v/=1024;i++}return`${v.toFixed(i?1:0)} ${u[i]}`}
function mode(){return document.querySelector('input[name="mode"]:checked').value}
function setProgress(p,t){E.bar.style.width=`${p}%`;E.pct.textContent=`${Math.round(p)}%`;E.status.textContent=t}
function applyPreset(n){document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('active',b.dataset.preset===n));if(n==='web'){E.maxPx.value=1920;E.maxMb.value=2;document.querySelector('[value="both"]').checked=true}if(n==='email'){E.maxPx.value=1600;E.maxMb.value=1;document.querySelector('[value="both"]').checked=true}}
function addFiles(list){for(const f of [...list]){if(!TYPES.has(f.type))continue;if(S.files.some(x=>x.file.name===f.name&&x.file.size===f.size&&x.file.lastModified===f.lastModified))continue;S.files.push({file:f,url:URL.createObjectURL(f),blob:null,name:null,error:null,custom:null})}render()}
function removeAt(i){URL.revokeObjectURL(S.files[i].url);S.files.splice(i,1);render()}
function render(){E.empty.hidden=S.files.length>0;E.selected.hidden=!S.files.length;E.count.textContent=S.files.length;E.grid.innerHTML='';S.files.forEach((x,i)=>{const c=document.createElement('div');c.className='thumb-card';c.innerHTML=`<img src="${x.url}" alt=""><div class="thumb-name"></div><div class="thumb-size"></div><div class="thumb-actions"><button class="edit-btn">調整</button><button class="remove-btn">移除</button></div>`;c.querySelector('.thumb-name').textContent=x.file.name;c.querySelector('.thumb-size').textContent=x.blob?`${fmt(x.file.size)} → ${fmt(x.blob.size)}`:fmt(x.file.size);c.querySelector('.edit-btn').onclick=()=>openEditor(i);c.querySelector('.remove-btn').onclick=()=>removeAt(i);E.grid.appendChild(c)});E.process.disabled=!S.files.length||S.processing;updateSummary();updateDownload()}
function updateSummary(){const a=S.files.reduce((s,x)=>s+x.file.size,0),d=S.files.filter(x=>x.blob),b=d.reduce((s,x)=>s+x.blob.size,0),oa=d.reduce((s,x)=>s+x.file.size,0);E.orig.textContent=fmt(a);E.out.textContent=d.length?fmt(b):'0 MB';E.saved.textContent=oa?`${Math.max(0,(oa-b)/oa*100).toFixed(1)}%`:'0%'}
function updateDownload(){const d=S.files.filter(x=>x.blob);E.download.disabled=!d.length||S.processing;E.download.textContent=d.length===1?'下載圖片':d.length>1?`全部下載 ZIP（${d.length} 張）`:'下載處理結果'}
async function bitmap(file){try{return await createImageBitmap(file,{imageOrientation:'from-image'})}catch{return await createImageBitmap(file)}}
function newCanvas(w,h){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c}
function drawContain(src,w,h){const c=newCanvas(w,h),ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(src,0,0,c.width,c.height);return c}
function rotateCanvas(src,deg){const d=((deg%360)+360)%360;if(!d)return drawContain(src,src.width,src.height);const swap=d===90||d===270,c=newCanvas(swap?src.height:src.width,swap?src.width:src.height),ctx=c.getContext('2d');ctx.translate(c.width/2,c.height/2);ctx.rotate(d*Math.PI/180);ctx.drawImage(src,-src.width/2,-src.height/2);return c}
function calcCentralCropRect(sw,sh,ratio){if(!ratio)return{sx:0,sy:0,cw:sw,ch:sh};const sr=sw/sh;let sx=0,sy=0,cw=sw,ch=sh;if(sr>ratio){cw=sh*ratio;sx=(sw-cw)/2}else{ch=sw/ratio;sy=(sh-ch)/2}return{sx,sy,cw,ch}}
function cropByRect(src,r){const c=newCanvas(r.cw,r.ch);c.getContext('2d').drawImage(src,r.sx,r.sy,r.cw,r.ch,0,0,c.width,c.height);return c}
function toBlob(c,t,q){return new Promise((r,j)=>c.toBlob(b=>b?r(b):j(new Error('無法產生圖片')),t,q))}
async function searchQ(c,t,max){let lo=.35,hi=.95,best=null;for(let i=0;i<8;i++){const q=(lo+hi)/2,b=await toBlob(c,t,q);if(b.size<=max){best=b;lo=q}else hi=q}return best||toBlob(c,t,.35)}
async function shrink(c,t,target){let cur=c,b=null;for(let i=0;i<12;i++){b=t==='image/png'?await toBlob(cur,t):await searchQ(cur,t,target);if(b.size<=target)return b;if(Math.max(cur.width,cur.height)<=320)break;cur=drawContain(cur,cur.width*.9,cur.height*.9)}return b}
function outName(name,t){const p=name.lastIndexOf('.'),base=p>=0?name.slice(0,p):name,ext=t==='image/jpeg'?'.jpg':t==='image/webp'?'.webp':'.png';return base+ext}
function alpha(c){const ctx=c.getContext('2d',{willReadFrequently:true}),w=c.width,h=c.height,step=Math.max(1,Math.floor(Math.sqrt(w*h/30000)));for(let y=0;y<h;y+=step){const row=ctx.getImageData(0,y,w,1).data;for(let x=0;x<w;x+=step)if(row[x*4+3]<255)return true}return false}
function normRect(r,w,h){const min=20;let sx=Math.max(0,Math.min(r.sx,w-min)),sy=Math.max(0,Math.min(r.sy,h-min)),cw=Math.max(min,Math.min(r.cw,w-sx)),ch=Math.max(min,Math.min(r.ch,h-sy));return{sx,sy,cw,ch}}
async function processOne(x){const b=await bitmap(x.file);try{let base=rotateCanvas(b,x.custom?.rotation||0),c;if(x.custom){if(x.custom.freeCrop&&x.custom.cropRect)c=cropByRect(base,normRect(x.custom.cropRect,base.width,base.height));else c=cropByRect(base,calcCentralCropRect(base.width,base.height,x.custom.ratio));c=drawContain(c,x.custom.width,x.custom.height)}else{const m=mode(),max=Number(E.maxPx.value),long=Math.max(base.width,base.height);if((m==='pixels'||m==='both')&&long>max){const r=max/long;c=drawContain(base,base.width*r,base.height*r)}else c=drawContain(base,base.width,base.height)}const m=mode(),target=Number(E.maxMb.value)*1024*1024,t=x.file.type;if(m==='pixels'){const blob=await toBlob(c,t,t==='image/png'?undefined:.9);return{blob,name:outName(x.file.name,t)}}if(t==='image/png'){const p=await toBlob(c,'image/png');if(p.size<=target)return{blob:p,name:outName(x.file.name,'image/png')};if(!alpha(c)&&E.convert.checked)return{blob:await shrink(c,'image/jpeg',target),name:outName(x.file.name,'image/jpeg')};return{blob:await shrink(c,'image/png',target),name:outName(x.file.name,'image/png')}}return{blob:await shrink(c,t,target),name:outName(x.file.name,t)}}finally{if(b.close)b.close()}}
async function processAll(){if(!S.files.length)return;S.processing=true;render();for(let i=0;i<S.files.length;i++){const x=S.files[i];setProgress(i/S.files.length*100,`正在處理：${x.file.name}`);try{const r=await processOne(x);x.blob=r.blob;x.name=r.name;x.error=null}catch(e){x.error=e.message}render();await new Promise(r=>setTimeout(r,0))}S.processing=false;setProgress(100,'處理完成');render()}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1200)}
async function downloadResults(){const d=S.files.filter(x=>x.blob);if(d.length===1)return downloadBlob(d[0].blob,d[0].name);const z=new JSZip(),used=new Set();for(const x of d){let n=x.name,k=2,p=n.lastIndexOf('.'),base=p>=0?n.slice(0,p):n,ext=p>=0?n.slice(p):'';while(used.has(n))n=`${base}_${k++}${ext}`;used.add(n);z.file(n,x.blob)}downloadBlob(await z.generateAsync({type:'blob'}),'resized_images.zip')}
function reset(){S.files.forEach(x=>URL.revokeObjectURL(x.url));S.files=[];setProgress(0,'準備就緒');render()}
async function openEditor(i){S.editorIndex=i;const x=S.files[i];if(S.editorBitmap&&S.editorBitmap.close)S.editorBitmap.close();S.editorBitmap=await bitmap(x.file);S.rotation=x.custom?.rotation||0;const dims=rotatedDims();S.editorRatio=dims.width/dims.height;S.freeCrop=Boolean(x.custom?.freeCrop);S.editorCrop=x.custom?.ratio||null;S.editorW=x.custom?.width||dims.width;S.editorH=x.custom?.height||dims.height;S.cropRect=x.custom?.cropRect?{...x.custom.cropRect}:{sx:0,sy:0,cw:dims.width,ch:dims.height};E.ename.textContent=x.file.name;E.modal.hidden=false;document.body.style.overflow='hidden';syncEditor()}
function closeEditor(){E.modal.hidden=true;document.body.style.overflow='';if(S.editorBitmap&&S.editorBitmap.close)S.editorBitmap.close();S.editorBitmap=null;S.pointerMode=null;S.drawingNewCrop=false}
function rotatedDims(){const d=((S.rotation%360)+360)%360;return(d===90||d===270)?{width:S.editorBitmap.height,height:S.editorBitmap.width}:{width:S.editorBitmap.width,height:S.editorBitmap.height}}
function currentSourceRect(){const d=rotatedDims();return S.freeCrop?normRect(S.cropRect,d.width,d.height):calcCentralCropRect(d.width,d.height,S.editorCrop)}
function getRotatedPreviewCanvas(){return rotateCanvas(S.editorBitmap,S.rotation)}
function syncEditor(){if(!S.editorBitmap)return;const rot=getRotatedPreviewCanvas(),d={width:rot.width,height:rot.height};E.odim.textContent=`${d.width} × ${d.height}`;const maxW=Math.min(window.innerWidth*.58,760),maxH=Math.min(window.innerHeight*.68,620),scale=Math.min(maxW/d.width,maxH/d.height,1);S.previewScale=scale;const dw=Math.round(d.width*scale),dh=Math.round(d.height*scale);E.stage.style.width=`${dw}px`;E.stage.style.height=`${dh}px`;E.canvas.width=dw;E.canvas.height=dh;E.canvas.style.width=`${dw}px`;E.canvas.style.height=`${dh}px`;const ctx=E.canvas.getContext('2d');ctx.clearRect(0,0,dw,dh);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(rot,0,0,dw,dh);const src=currentSourceRect();E.ew.value=Math.round(S.editorW);E.eh.value=Math.round(S.editorH);E.cdim.textContent=`${Math.round(S.editorW)} × ${Math.round(S.editorH)}`;const pct=Math.round(S.editorW/src.cw*100);E.slider.value=Math.max(10,Math.min(300,pct));E.scaleVal.textContent=`${pct}%`;document.querySelectorAll('.ratio').forEach(b=>b.classList.toggle('active',(b.dataset.ratio==='original'&&!S.editorCrop)||Number(b.dataset.ratio)===S.editorCrop));E.freeCropBtn.classList.toggle('active',S.freeCrop);E.cropInfoRow.hidden=!S.freeCrop;E.stage.classList.toggle('draw-crop',S.drawingNewCrop);if(S.freeCrop){const l=src.sx*scale,t=src.sy*scale,w=src.cw*scale,h=src.ch*scale;E.cropBox.hidden=false;E.cropBox.style.left=`${l}px`;E.cropBox.style.top=`${t}px`;E.cropBox.style.width=`${w}px`;E.cropBox.style.height=`${h}px`;E.cropDim.textContent=`${Math.round(src.cw)} × ${Math.round(src.ch)}`;E.cropBoxSize.textContent=`${Math.round(src.cw)}×${Math.round(src.ch)}`}else E.cropBox.hidden=true;updateFinalPreview(rot,src);}
function updateFinalPreview(rot,src){const max=420,r=Math.min(max/src.cw,220/src.ch,1),w=Math.max(1,Math.round(src.cw*r)),h=Math.max(1,Math.round(src.ch*r));E.finalPreviewCanvas.width=w;E.finalPreviewCanvas.height=h;E.finalPreviewCanvas.getContext('2d').drawImage(rot,src.sx,src.sy,src.cw,src.ch,0,0,w,h);E.finalPreviewDim.textContent=`${Math.round(src.cw)} × ${Math.round(src.ch)}`}
function setWidth(w){S.editorW=Math.max(1,Math.round(w));if(E.lock.checked){const r=currentSourceRect();S.editorH=Math.max(1,Math.round(S.editorW/(r.cw/r.ch)))}syncEditor()}
function setHeight(h){S.editorH=Math.max(1,Math.round(h));if(E.lock.checked){const r=currentSourceRect();S.editorW=Math.max(1,Math.round(S.editorH*(r.cw/r.ch)))}syncEditor()}
function setScale(p){const r=currentSourceRect();S.editorW=Math.max(1,Math.round(r.cw*p/100));S.editorH=Math.max(1,Math.round(S.editorW/(r.cw/r.ch)));syncEditor()}
function resetCropRect(){const d=rotatedDims();S.cropRect={sx:0,sy:0,cw:d.width,ch:d.height};if(S.freeCrop){S.editorW=d.width;S.editorH=d.height}syncEditor()}
function toggleFreeCrop(){S.freeCrop=!S.freeCrop;S.drawingNewCrop=false;if(S.freeCrop){if(!S.cropRect)resetCropRect();const d=rotatedDims();if(S.editorCrop){const ratio=S.editorCrop;let cw=d.width*.8,ch=cw/ratio;if(ch>d.height*.8){ch=d.height*.8;cw=ch*ratio}S.cropRect={sx:(d.width-cw)/2,sy:(d.height-ch)/2,cw,ch}}const r=currentSourceRect();S.editorW=r.cw;S.editorH=r.ch}syncEditor()}
function startNewCrop(){S.freeCrop=true;S.drawingNewCrop=true;E.freeCropBtn.classList.add('active');syncEditor()}
function rotateBy(delta){S.rotation=(S.rotation+delta+360)%360;S.freeCrop=false;S.editorCrop=null;S.drawingNewCrop=false;const d=rotatedDims();S.cropRect={sx:0,sy:0,cw:d.width,ch:d.height};S.editorW=d.width;S.editorH=d.height;S.editorRatio=d.width/d.height;syncEditor()}
function pointerPos(e){const r=E.stage.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function startPointer(e,type){e.preventDefault();e.stopPropagation();S.pointerMode=type;S.startPoint=pointerPos(e);S.startCropRect={...S.cropRect}}
function stagePointerDown(e){if(!S.drawingNewCrop)return;e.preventDefault();const p=pointerPos(e),d=rotatedDims();S.pointerMode='draw-crop';S.startPoint=p;S.cropRect={sx:clamp(p.x/S.previewScale,0,d.width-20),sy:clamp(p.y/S.previewScale,0,d.height-20),cw:20,ch:20};syncEditor()}
function onPointerMove(e){if(!S.pointerMode||!S.editorBitmap)return;const p=pointerPos(e),dx=(p.x-S.startPoint.x)/S.previewScale,dy=(p.y-S.startPoint.y)/S.previewScale,d=rotatedDims();if(S.pointerMode==='draw-crop'){let x1=S.startPoint.x/S.previewScale,y1=S.startPoint.y/S.previewScale,x2=p.x/S.previewScale,y2=p.y/S.previewScale;let sx=Math.min(x1,x2),sy=Math.min(y1,y2),cw=Math.abs(x2-x1),ch=Math.abs(y2-y1);if(S.editorCrop){const ratio=S.editorCrop;if(cw/Math.max(ch,1)>ratio)cw=ch*ratio;else ch=cw/ratio;if(x2<x1)sx=x1-cw;if(y2<y1)sy=y1-ch}let r={sx,sy,cw,ch};S.cropRect=normRect(r,d.width,d.height);S.editorW=S.cropRect.cw;S.editorH=S.cropRect.ch;syncEditor();return}if(S.pointerMode==='move-crop'){let r={...S.startCropRect};r.sx=clamp(r.sx+dx,0,d.width-r.cw);r.sy=clamp(r.sy+dy,0,d.height-r.ch);S.cropRect=normRect(r,d.width,d.height);syncEditor();return}if(S.pointerMode.startsWith('edge-')||S.pointerMode.startsWith('corner-')){let r={...S.startCropRect};const key=S.pointerMode.split('-')[1];if(key.includes('e'))r.cw=S.startCropRect.cw+dx;if(key.includes('s'))r.ch=S.startCropRect.ch+dy;if(key.includes('w')){r.sx=S.startCropRect.sx+dx;r.cw=S.startCropRect.cw-dx}if(key.includes('n')){r.sy=S.startCropRect.sy+dy;r.ch=S.startCropRect.ch-dy}const fixed=S.editorCrop||(E.lock.checked&&key.length===2?S.startCropRect.cw/S.startCropRect.ch:null);if(fixed){if(key==='e'||key==='w'||Math.abs(dx)>=Math.abs(dy)){r.ch=r.cw/fixed;if(key.includes('n'))r.sy=S.startCropRect.sy+(S.startCropRect.ch-r.ch)}else{r.cw=r.ch*fixed;if(key.includes('w'))r.sx=S.startCropRect.sx+(S.startCropRect.cw-r.cw)}}S.cropRect=normRect(r,d.width,d.height);S.editorW=Math.round(S.cropRect.cw);S.editorH=Math.round(S.cropRect.ch);syncEditor();return}if(S.pointerMode==='resize-output'){const nw=Math.max(1,Math.round(S.startCropRect.w+dx));if(E.lock.checked)setWidth(nw);else{S.editorW=nw;S.editorH=Math.max(1,Math.round(S.startCropRect.h+dy));syncEditor()}}}
function onPointerUp(){if(S.pointerMode==='draw-crop')S.drawingNewCrop=false;S.pointerMode=null;syncEditor()}
async function applyEdit(download=false){const x=S.files[S.editorIndex];x.custom={width:Math.round(S.editorW),height:Math.round(S.editorH),ratio:S.editorCrop,freeCrop:S.freeCrop,cropRect:S.freeCrop?{...normRect(S.cropRect,rotatedDims().width,rotatedDims().height)}:null,rotation:S.rotation};const r=await processOne(x);x.blob=r.blob;x.name=r.name;render();if(download)downloadBlob(x.blob,x.name);else closeEditor()}
E.choose.onclick=()=>E.file.click();E.add.onclick=()=>E.file.click();E.file.onchange=()=>addFiles(E.file.files);['dragenter','dragover'].forEach(t=>E.drop.addEventListener(t,e=>{e.preventDefault();E.drop.classList.add('dragover')}));['dragleave','drop'].forEach(t=>E.drop.addEventListener(t,e=>{e.preventDefault();E.drop.classList.remove('dragover')}));E.drop.addEventListener('drop',e=>addFiles(e.dataTransfer.files));document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));E.process.onclick=processAll;E.download.onclick=downloadResults;E.reset.onclick=reset;document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeEditor);E.ew.onchange=()=>setWidth(Number(E.ew.value));E.eh.onchange=()=>setHeight(Number(E.eh.value));E.slider.oninput=()=>setScale(Number(E.slider.value));document.querySelectorAll('[data-scale]').forEach(b=>b.onclick=()=>setScale(Number(b.dataset.scale)));E.fit1920.onclick=()=>setWidth(Math.min(1920,currentSourceRect().cw));document.querySelectorAll('.ratio').forEach(b=>b.onclick=()=>{S.drawingNewCrop=false;S.editorCrop=b.dataset.ratio==='original'?null:Number(b.dataset.ratio);if(S.freeCrop&&S.editorCrop){const d=rotatedDims(),cur=normRect(S.cropRect,d.width,d.height),cx=cur.sx+cur.cw/2,cy=cur.sy+cur.ch/2,ratio=S.editorCrop;let cw=cur.cw,ch=cw/ratio;if(ch>cur.ch){ch=cur.ch;cw=ch*ratio}if(cw>d.width){cw=d.width;ch=cw/ratio}if(ch>d.height){ch=d.height;cw=ch*ratio}let sx=clamp(cx-cw/2,0,d.width-cw),sy=clamp(cy-ch/2,0,d.height-ch);S.cropRect={sx,sy,cw,ch}}const r=currentSourceRect();S.editorW=r.cw;S.editorH=r.ch;syncEditor()});E.freeCropBtn.onclick=toggleFreeCrop;E.newCropBtn.onclick=startNewCrop;E.resetCropBtn.onclick=resetCropRect;E.rotateLeftBtn.onclick=()=>rotateBy(-90);E.rotateRightBtn.onclick=()=>rotateBy(90);E.apply.onclick=()=>applyEdit(false);E.downloadEdit.onclick=()=>applyEdit(true);E.cropBox.addEventListener('pointerdown',e=>{if(e.target!==E.cropBox&&e.target!==E.cropBox.querySelector('.crop-title'))return;startPointer(e,'move-crop')});document.querySelectorAll('.crop-edge').forEach(h=>h.addEventListener('pointerdown',e=>startPointer(e,`edge-${h.dataset.edge}`)));document.querySelectorAll('.crop-corner').forEach(h=>h.addEventListener('pointerdown',e=>startPointer(e,`corner-${h.dataset.corner}`)));E.resizeHandle.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();S.pointerMode='resize-output';S.startPoint=pointerPos(e);S.startCropRect={w:S.editorW,h:S.editorH}});E.stage.addEventListener('pointerdown',stagePointerDown);window.addEventListener('pointermove',onPointerMove);window.addEventListener('pointerup',onPointerUp);window.addEventListener('resize',()=>{if(!E.modal.hidden)syncEditor()});render();applyPreset('web');setProgress(0,'準備就緒');
